---
functional:
  - Возможность авторизации через Github
  - Возможность авторизации и голосового чата через Discord
  - Ведение рейтинга игроков по неделе/месяцу/всего и отображение на главной странице. Возможность сортировки по рейтингу, количеству игр и т.д.
  - Возможность просмотра истории баттлов
  - Возможность просмотра повтора баттла
  - Возможность выбора языка программирования в терминале баттла
  - Мультиязычность задач (русский и английский)
  - Поддержка всех популярных языков программирования
  - Уведомление о начале баттла
  - Установка таймера, регулирующего ход игрока
  - Возможность просмотра баттла зрителям в режиме online
  - Возможность организации турниров и турнирной сетки
  - Возможность переподключения участника к баттлу
  - После определения победителя должна быть возможность остаться в баттле и дописать код / ознакомиться с кодом
  - В истории есть иконка напротив никнейма, указывающая на победителя баттла
  - Возможность игры с ботом по готовым сценариям
  - Возможнсоть выбрать игру по уровню сложности
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователей
  - Сайт должен быть адаптирован для мобильных устройств
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быстро восстанавиваться в случае потери связи с базой данных
implicit:
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла
  - Зрители могут комментировать текующую игру в режиме реального времени
  - Возможность сортировки истории баттлов
  - Уведомление о начале баттла на почту пользователя
  - Возможность пригласить в игру по ссылке
  - Мультиязычность сайта
  - Чат для участников турнира
